### ISSUE TITLE
Merging into llama cpp or standalone : question 

### ISSUE THREAD

**Issue by x4080** [FSSRepo/llama.cpp#3]
Hi again, how do you plan on updating this repo when llama cpp is updated?

Is there an easy way to just copy from llama cpp and doing your build? Haven't investigate it yet though 

Thanks

**Comment by FSSRepo** [comment]
I will try to request to merge this fork with the master branch of llama.cpp, Now, I will do some corrections and update the lastest version of llama.cpp

**Comment by x4080** [comment]
Allright, cant wait for it
